Rework and improvements of ExWilderness
rs-peer/extended-api pull request #20
Opened 2019-09-25 11:12 UTC by Typiqally

# Rework and improvements of ExWilderness

Figured I would rework and share this code since I'm going to use it in my script. I hope it lives up to RSPeer's standards.

2019-09-25 22:02 UTC, maddalax requested changes
Looks really good, thanks for improving this. Just had 2 comments.

2019-09-25 22:02 UTC, maddalax commented on src/org/rspeer/runetek/api/component/ExWilderness.java
> +        // If target player is contained within one of these areas (there are probably more) then return true
I would add a check here if the player passed in is local player, then return the other isInWilderness check, that way it can check the interface.

2019-09-25 22:02 UTC, MaddoxDevelopment commented on src/org/rspeer/runetek/api/component/ExWilderness.java
> +        // If the warning is open, approve the warning and sleep till it is no longer open
```
if(isWarningOpen() && approveWarning(remember)) { 
   
}
```

2019-09-25 22:07 UTC, MaddoxDevelopment commented
Webhook test.

2019-09-25 22:13 UTC, Sphiinx commented
Good to see someone creating a pull request and improving the wilderness API I added awhile back 😃 

Good job!

2019-09-25 22:24 UTC, MaddoxDevelopment commented
> Good to see someone creating a pull request and improving the wilderness API I added awhile back 😃
> 
> Good job!

So you are the one to blame for the snake case...

2019-09-25 22:37 UTC, Sphiinx commented
> > Good to see someone creating a pull request and improving the wilderness API I added awhile back 😃
> > Good job!
> 
> So you are the one to blame for the snake case...

Oh yeah I am :)

2019-09-26 05:27 UTC, Typiqally commented
All comments should now be resolved and fixed, thanks for the good words :)

2019-09-26 14:58 UTC, maddalax approved these changes

2019-09-26 14:58 UTC, merged